version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: assembleia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  postgres_data:
  redis_data: