spring:

  application:
    name: integracao_logistica

  sessao_votacao:
    encerramento:
      tempo:
        ms: 5000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username:  ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    queue:
      voto:
        nome: voto-queue
        dlq: voto-queue-dlq
      sessao_votacao_encerramento:
        nome: sessao-votacao-encerramento

  datasource:
    url: jdbc:postgresql://postgres:5432/assembleia
    username:  ${POSTGRES_USER}
    password: ${POSTGRES_DB}

  data:
    redis:
      host: redis
      port: 6379
      sessao_votacao_cache:
        ttl: 86400

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO