spring:

  application:
    name: integracao_logistica

  sessao_votacao:
    encerramento:
      tempo:
        ms: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      voto:
        nome: voto-queue
        dlq: voto-queue-dlq
      sessao_votacao_encerramento:
        nome: sessao-votacao-encerramento

  datasource:
    url: jdbc:postgresql://localhost:5432/assembleia
    username: postgres
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379
      sessao_votacao_cache:
        ttl: 86400

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO


