CREATE TABLE public.voto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    associado_id BIGINT NULL,
    sessao_id    BIGINT NULL,
    voto_enum    varchar(255) NOT NULL,
    CONSTRAINT voto_pkey PRIMARY KEY (id),
    CONSTRAINT voto_voto_enum_check CHECK (((voto_enum)::text = ANY ((ARRAY['SIM':: character varying, 'NAO':: character varying])::text[])
) ),
	CONSTRAINT fk_associado_id_to_associado FOREIGN KEY (associado_id) REFERENCES public.associado(id),
	CONSTRAINT fk_sessao_id_to_sessao_votacao FOREIGN KEY (sessao_id) REFERENCES public.sessao_votacao(id)
);